version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json
    schedule:
      interval: "weekly"
    # Only update prod dependencies, ignore devDependencies
    allow:
      - dependency-type: "production"
