version: '2.1'

services:

  cxbox-demo-node-1:
    image: 'cxbox/demo:${APP_IMAGE_TAG}'
    environment:
      FRONTEND_AUTH_SERVER_URL: 'http://demo.cxbox.org:9080/auth/'
      BACKEND_AUTH_SERVER_URL: 'http://demo.cxbox.org:9080/auth/'
      DEV_PANEL_ENABLED: 'true'
      META_DIRECTORY: 'classpath:meta'
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://cxbox_postgres:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      MINIO_ACCESS_KEY: '4eb6a7db8b58994ea61b'
      MINIO_SECRET_KEY: 'prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW'
      MINIO_URL: 'http://cxbox_minio:9000'
      MINIO_DEFAULT_BUCKETS: 'edcs3gnsadevb'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n'
    expose:
      - 8080
    ports:
      - "0.0.0.0:8081:8080"
      - "127.0.0.1:8981:8989"
    restart: always

  cxbox-demo-node-2:
    image: 'cxboxplatform/demo:${APP_IMAGE_TAG}'
    environment:
      FRONTEND_AUTH_SERVER_URL: 'http://demo.cxbox.org:9080/auth/'
      BACKEND_AUTH_SERVER_URL: 'http://demo.cxbox.org:9080/auth/'

      DEV_PANEL_ENABLED: 'true'
      META_DIRECTORY: 'classpath:meta'
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://cxbox_postgres:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      MINIO_ACCESS_KEY: '4eb6a7db8b58994ea61b'
      MINIO_SECRET_KEY: 'prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW'
      MINIO_URL: 'http://cxbox_minio:9000'
      MINIO_DEFAULT_BUCKETS: 'edcs3gnsadevb'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n'
    expose:
      - 8080
    ports:
      - "0.0.0.0:8082:8080"
      - "127.0.0.1:8982:8989"
    restart: always

  cxbox_postgres:
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
  keycloak:
    image: jboss/keycloak:12.0.4
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled'
      ]
    volumes:
      - ./docker/keycloak-config:/opt/jboss/keycloak/realm-config
      - ./.tmp/keycloak-db:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    expose:
      - 9080
    ports:
      - "127.0.0.1:9080:9080"
      - "127.0.0.1:9443:9443"
      - "127.0.0.1:10990:10990"

  cxbox_minio:
    image: bitnami/minio:2022.2.12
    expose:
      - 9000
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "4eb6a7db8b58994ea61b"
      MINIO_ROOT_PASSWORD: "prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW"
      MINIO_DEFAULT_BUCKETS: "edcs3gnsadevb"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates/:/etc/nginx/templates/
    environment:
      CXBOX_APP_1: 'cxbox-demo-node-1:8080'
      CXBOX_APP_2: 'cxbox-demo-node-2:8080'
      KEYCLOAK_1: 'keycloak:9080'
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - cxbox-demo-node-1
      - cxbox-demo-node-2