app:
  ui-path: /ui
  keycloak:
    realm: cxbox
    auth-server-url: ${FRONTEND_AUTH_SERVER_URL:http://localhost:9080/auth}
    ssl-require: none
    resource: cxbox-keycloak-client
    public-client: true
    cors: true

cxbox:
  bean:
    multipart-resolver:
      enabled: false
  meta:
    dev-panel-enabled: ${DEV_PANEL_ENABLED:true}
    directory: ${META_DIRECTORY:file:./src/main/resources/meta}
    view-allowed-roles-enabled: true
  widget:
    fields:
      include-packages: org.cxbox.core.ui.model.json.field.subtypes, org.demo.conf.cxbox.meta
  api:
    path: /api/v1
  ui:
    path: /ui

server:
  port : 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    name: primaryDS
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    drop-first: true
    contexts: local
  cache:
    type: None
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
    hibernate:
      naming:
        physical-strategy: org.cxbox.model.core.hbn.ImprovedPhysicalNamingStrategy
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
  main:
    allow-bean-definition-overriding: true
    banner-mode: off

keycloak:
  auth-server-url: ${BAKEND_AUTH_SERVER_URL:http://localhost:9080/auth}
  realm: cxbox
  resource: cxbox-keycloak-client
  bearer-only: true
  public-client: true
  use-resource-role-mappings: true
  ssl-required: none
springdoc:
  packages-to-scan: org.demo

minio:
  access:
    name: ${MINIO_ACCESS_KEY:4eb6a7db8b58994ea61b}
    secret: ${MINIO_SECRET_KEY:prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW}
  url: ${MINIO_URL:http://localhost:9000}
  bucket:
    name: ${MINIO_DEFAULT_BUCKETS:edcs3gnsadevb}