UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '4' DAY,
    end_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '4' DAY + INTERVAL '23' HOUR + INTERVAL '59' MINUTE
WHERE id = 1000055;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '8' DAY,
    end_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '12' DAY + INTERVAL '23' HOUR + INTERVAL '59' MINUTE
WHERE id = 1000056;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '9' DAY + INTERVAL '10' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '9' DAY + INTERVAL '11' HOUR + INTERVAL '30' MINUTE
WHERE id = 1000057;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '17' DAY + INTERVAL '14' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '17' DAY + INTERVAL '16' HOUR
WHERE id = 1000058;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '24' DAY + INTERVAL '9' HOUR + INTERVAL '30' MINUTE,
    end_date_time = TRUNC(SYSDATE, 'MM') - INTERVAL '1' MONTH + INTERVAL '24' DAY + INTERVAL '11' HOUR
WHERE id = 1000059;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '2' DAY,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '2' DAY + INTERVAL '23' HOUR + INTERVAL '59' MINUTE
WHERE id = 1000060;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '9' DAY,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '13' DAY + INTERVAL '23' HOUR + INTERVAL '59' MINUTE
WHERE id = 1000061;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '11' DAY + INTERVAL '10' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '11' DAY + INTERVAL '12' HOUR
WHERE id = 1000062;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '16' DAY + INTERVAL '14' HOUR + INTERVAL '30' MINUTE,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '16' DAY + INTERVAL '16' HOUR + INTERVAL '30' MINUTE
WHERE id = 1000063;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '23' DAY + INTERVAL '9' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '23' DAY + INTERVAL '11' HOUR
WHERE id = 1000064;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '27' DAY + INTERVAL '15' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '27' DAY + INTERVAL '16' HOUR + INTERVAL '30' MINUTE
WHERE id = 1000065;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '23' HOUR + INTERVAL '59' MINUTE
WHERE id = 1000066;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '5' DAY,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '9' DAY + INTERVAL '23' HOUR + INTERVAL '59' MINUTE
WHERE id = 1000067;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '7' DAY + INTERVAL '10' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '7' DAY + INTERVAL '12' HOUR
WHERE id = 1000068;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '14' DAY + INTERVAL '13' HOUR + INTERVAL '30' MINUTE,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '14' DAY + INTERVAL '17' HOUR + INTERVAL '30' MINUTE
WHERE id = 1000069;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '21' DAY + INTERVAL '9' HOUR + INTERVAL '30' MINUTE,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '21' DAY + INTERVAL '11' HOUR + INTERVAL '30' MINUTE
WHERE id = 1000070;

UPDATE meeting
SET
    start_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '28' DAY + INTERVAL '14' HOUR,
    end_date_time = TRUNC(SYSDATE, 'MM') + INTERVAL '1' MONTH + INTERVAL '28' DAY + INTERVAL '16' HOUR
WHERE id = 1000071;