const VERTICAL_PADDING = 4
const TOOLBAR_HEIGHT = 30

export const ONE_ROW_TEXTAREA_VERTICAL_PADDING_OFFSET = 2 * VERTICAL_PADDING
export const COMMON_TEXTAREA_VERTICAL_PADDING_OFFSET = ONE_ROW_TEXTAREA_VERTICAL_PADDING_OFFSET - TOOLBAR_HEIGHT
