name: Build project

on: [push, workflow_dispatch]

jobs:
  build11:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Build with Maven
        run: mvn clean install -PUI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Build with Maven
        run: mvn clean install -PUI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}