name: Build project

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ '8', '11']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.Java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Build with Maven
        run: mvn clean install -PUI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}